-- =====================================================
-- GAME ATTENDANCE VIEWS - SCAN-BASED (ACTUAL ATTENDANCE)
-- Uses V_FACT_INDIVIDUAL_SEAT_SALES with IS_SCANNED = 1
-- This captures ALL buyer types including sponsors
-- =====================================================

-- DETAIL VIEW: Individual game attendance records
CREATE OR REPLACE VIEW TBRDP_DW_PROD.IM_RPT.V_CUSTOMER_GAME_ATTENDANCE_DETAIL AS
SELECT 
    c.PATRON_ACCOUNT_ID_BK AS FINANCIAL_PATRON_ACCOUNT_ID,
    c.PATRON_ACCOUNT_NAME,
    c.EMAIL,
    c.FIRST_NAME,
    c.LAST_NAME,
    gd.GAME_YEAR AS SEASON_YEAR,
    gd.GAME_DATE,
    gd.EVENT_DESCRIPTION AS EVENT_NAME,
    gd.EVENT_ID_BK AS EVENT_ID,
    gd.AWAY_TEAM_CODE AS OPPONENT,
    gr.GAMEPK,
    gr.HOME_TEAM,
    gr.AWAY_TEAM,
    gr.HOME_SCORE,
    gr.AWAY_SCORE,
    gr.RAYS_WIN,
    gr.RAYS_HOME,
    CASE WHEN gr.RAYS_WIN THEN 'WIN' ELSE 'LOSS' END AS GAME_RESULT,
    tt.BUYER_TYPE_GROUP_DESCRIPTION,
    tt.BUYER_TYPE_DESCRIPTION,
    tt.TICKET_TYPE_STANDARD,
    SUM(f.TICKETS) AS TICKETS_PURCHASED,
    SUM(f.PRICE) AS TICKET_SPEND
FROM TBRDP_DW_PROD.IM_RPT.V_FACT_INDIVIDUAL_SEAT_SALES f
INNER JOIN TBRDP_DW_PROD.IM_RPT.V_DIM_CUSTOMER__ATTENDING c 
    ON f.V_DIM_CUSTOMER__ATTENDING_KEY = c.V_DIM_CUSTOMER__ATTENDING_KEY
INNER JOIN TBRDP_DW_PROD.IM_RPT.V_DIM_TICKET_TYPE tt 
    ON f.V_DIM_TICKET_TYPE_KEY = tt.V_DIM_TICKET_TYPE_KEY
INNER JOIN TBRDP_DW_PROD.IM_RPT.V_DIM_GAME_DATE gd 
    ON f.V_DIM_GAME_DATE_KEY = gd.V_DIM_GAME_DATE_KEY
LEFT JOIN TBRDP_DW_PROD.IM_RPT.T_GAME_RESULTS gr 
    ON DATE(gd.GAME_DATE) = gr.GAME_DATE
WHERE f.IS_SCANNED = 1
  AND gd.GAME_YEAR IN (2023, 2024, 2025)
  AND c.PATRON_ACCOUNT_ID_BK IS NOT NULL
GROUP BY 
    c.PATRON_ACCOUNT_ID_BK,
    c.PATRON_ACCOUNT_NAME,
    c.EMAIL,
    c.FIRST_NAME,
    c.LAST_NAME,
    gd.GAME_YEAR,
    gd.GAME_DATE,
    gd.EVENT_DESCRIPTION,
    gd.EVENT_ID_BK,
    gd.AWAY_TEAM_CODE,
    gr.GAMEPK,
    gr.HOME_TEAM,
    gr.AWAY_TEAM,
    gr.HOME_SCORE,
    gr.AWAY_SCORE,
    gr.RAYS_WIN,
    gr.RAYS_HOME,
    tt.BUYER_TYPE_GROUP_DESCRIPTION,
    tt.BUYER_TYPE_DESCRIPTION,
    tt.TICKET_TYPE_STANDARD;


-- SUMMARY VIEW: Aggregated attendance metrics per customer
CREATE OR REPLACE VIEW TBRDP_DW_PROD.IM_RPT.V_CUSTOMER_GAME_ATTENDANCE AS
SELECT 
    FINANCIAL_PATRON_ACCOUNT_ID,
    COUNT(DISTINCT GAMEPK) AS GAMES_ATTENDED,
    COUNT(DISTINCT CASE WHEN RAYS_WIN = TRUE THEN GAMEPK END) AS GAMES_WON,
    COUNT(DISTINCT CASE WHEN RAYS_WIN = FALSE THEN GAMEPK END) AS GAMES_LOST,
    ROUND(COUNT(DISTINCT CASE WHEN RAYS_WIN = TRUE THEN GAMEPK END) * 100.0 / NULLIF(COUNT(DISTINCT GAMEPK), 0), 1) AS WIN_PCT_ATTENDED,
    SUM(TICKET_SPEND) AS TOTAL_TICKET_SPEND,
    ROUND(AVG(TICKET_SPEND), 2) AS AVG_TICKET_PRICE,
    MIN(GAME_DATE) AS FIRST_GAME_DATE,
    MAX(GAME_DATE) AS LAST_GAME_DATE,
    COUNT(DISTINCT SEASON_YEAR) AS SEASONS_ATTENDED_COUNT,
    ARRAY_TO_STRING(ARRAY_AGG(DISTINCT SEASON_YEAR) WITHIN GROUP (ORDER BY SEASON_YEAR), ', ') AS SEASONS_ATTENDED
FROM TBRDP_DW_PROD.IM_RPT.V_CUSTOMER_GAME_ATTENDANCE_DETAIL
WHERE GAMEPK IS NOT NULL
GROUP BY FINANCIAL_PATRON_ACCOUNT_ID;
