-- =====================================================
-- GAME ATTENDANCE DETAIL VIEW
-- Shows individual game attendance records with outcomes
-- =====================================================

CREATE OR REPLACE VIEW TBRDP_DW_PROD.IM_RPT.V_CUSTOMER_GAME_ATTENDANCE_DETAIL AS
SELECT 
    t.FINANCIAL_PATRON_ACCOUNT_ID,
    t.PATRON_ACCOUNT_NAME,
    t.EMAIL,
    t.SEASON_YEAR,
    g.GAME_DATE,
    t.EVENT_NAME,
    g.GAMEPK,
    g.HOME_TEAM,
    g.AWAY_TEAM,
    g.OPPONENT,
    g.HOME_SCORE,
    g.AWAY_SCORE,
    g.RAYS_WIN,
    g.RAYS_HOME,
    CASE WHEN g.RAYS_WIN THEN 'WIN' ELSE 'LOSS' END AS GAME_RESULT,
    COUNT(*) AS TICKETS_PURCHASED,
    SUM(t.PRICE) AS TICKET_SPEND
FROM TBRDP_DW_PROD.IM_RPT.V_SBL_GCP_TDC_REGULAR_SEASON_TICKET_DETAIL t
JOIN TBRDP_DW_PROD.IM_RPT.T_EVENT_CROSSWALK x ON t.EVENT_ID = x.EVENT_ID
JOIN TBRDP_DW_PROD.IM_RPT.T_GAME_RESULTS g ON x.GAMEPK = g.GAMEPK
WHERE t.SYSTEM_CURRENT_FLAG = 'Y'
  AND t.SEASON_YEAR >= 2023
GROUP BY 
    t.FINANCIAL_PATRON_ACCOUNT_ID,
    t.PATRON_ACCOUNT_NAME,
    t.EMAIL,
    t.SEASON_YEAR,
    g.GAME_DATE,
    t.EVENT_NAME,
    g.GAMEPK,
    g.HOME_TEAM,
    g.AWAY_TEAM,
    g.OPPONENT,
    g.HOME_SCORE,
    g.AWAY_SCORE,
    g.RAYS_WIN,
    g.RAYS_HOME;
